### PR TITLE
Add multiline functionality

### PR DESCRIPTION
**Pull request by Tooflex**
Refactor Code and Add Multiline Text Entry Support

This pull request addresses issue #19. It introduces multiline text entry functionality, enhancing user input capabilities.

The changes include:
- Refactoring the code following MVVM framework for better readability and maintainability.
- Implementing multiline support in the TextEditor component of ABC feature.

### CODE REVIEW

**Comment by kghandour** [comment]
Thank you for your contribution! With the holidays, I was unable to review the code but I am planning to get to it as soon as possible. 
However, I can see that you are changing the code structure from MVC to MVVM. Even though there are arguments for both approaches, as this is a smaller client with not a lot of views (Currently just 2 main ones, with a possible 3rd for multi-modal), I would like to stay with MVC. 
From a first glance, I can see that you did separate the functions better than what I am currently doing. It would be great if you update the PR such that we still keep the MVC architecture while moving the functions from the view to the controllers like you were able to. 
Would that be possible?

**Review by kghandour — CHANGES_REQUESTED** [review]
Thank you for your contribution! With the holidays, I was unable to review the code but I am planning to get to it as soon as possible.
However, I can see that you are changing the code structure from MVC to MVVM. Even though there are arguments for both approaches, as this is a smaller client with not a lot of views (Currently just 2 main ones, with a possible 3rd for multi-modal), I would like to stay with MVC.
From a first glance, I can see that you did separate the functions better than what I am currently doing. It would be great if you update the PR such that we still keep the MVC architecture while moving the functions from the view to the controllers like you were able to.
Would that be possible?

**Comment by Tooflex** [comment]
Yes I can do that 😊

**Comment by kghandour** [comment]
I have modified the codebase to fix some issues. If you are currently busy, I can cherry-pick the multiline commit and perform the refactoring myself. That way your contribution is still recorded. Let me know if that is better for you :)

**Comment by Tooflex** [comment]
Yes it's good for me 🙂

**Comment by zjwhitehead** [comment]
Excited to see this as a feature! Definitely hard to paste in multiple lines of code and see what I am doing.

**Comment by kghandour** [comment]
I was unable cherry-pick the commit due to a lot of changes in my refactoring. However, I've added your name to the README. Looking forward to your next contribution. Closing as texteditor is being used now with d82e58c4fbaec7137876f754b1e924d28c255361

**Pull request closed without merging**
